#数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.1.11:3306/docker_db_ssm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: jack123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml


server:
  port: 9090
